/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package yy.logcatcher;

import java.util.ArrayList;
import java.util.List;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollExceptionHandler;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;


public class PipeExceptionHandler implements KrollExceptionHandler
{
	private TiApplication app;
	private List<KrollModule> listeners = new ArrayList<KrollModule>();
	
	public PipeExceptionHandler(TiApplication app)
	{
		super();
		this.app = app;
	}

	@Override
	public void handleException(ExceptionMessage ex) {
		KrollDict data = new KrollDict();
		data.put("title", ex.title);
		data.put("sourceName", ex.sourceName);
		data.put("line", ex.line);
		data.put("lineOffset", ex.lineOffset);
		data.put("message", ex.message);
		data.put("lineSource", ex.lineSource);
		if (this.listeners.size() > 0) {
			for (KrollModule listener: listeners) {
				listener.fireEvent("error", data);
			}
		} else {
			this.app.fireAppEvent("error", data);
		}
		
	}
	
	public void addListener(KrollModule listener) {
		Log.d("PIPEEX", "adding listener");
		this.listeners.add(listener);
	}

}

