/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package yy.logcatcher;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

import org.appcelerator.kroll.KrollLogging;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.KrollRuntime;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;

import yy.logcatcher.PipeExceptionHandler;
import yy.logcatcher.PipeLogListener;


@Kroll.module(name="Tilogcatcher", id="yy.logcatcher")
public class TilogcatcherModule extends KrollModule
{
	
	// Standard Debugging variables
	private static PipeExceptionHandler ex;
	private static PipeLogListener log;


	public TilogcatcherModule()
	{
		super();
		ex.addListener(this);
		log.addListener(this);
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		ex = new PipeExceptionHandler(app);
		log = new PipeLogListener(app);
		KrollRuntime.addAdditionalExceptionHandler(ex, "errorEvent");
		KrollLogging.getDefault().setLogListener(log);
	}

	@Kroll.method
	public String getDeviceLogs() {
		try {
			Process process = Runtime.getRuntime().exec("logcat -d");
			BufferedReader bufferedReader = new BufferedReader(
					new InputStreamReader(process.getInputStream()));

			StringBuilder log = new StringBuilder();
			String line;
			while ((line = bufferedReader.readLine()) != null) {
				log.append(line + "\n");
			}
			return log.toString();
		} catch (IOException e) {
			return "";
		}
	}

}

